// Package icon holds doted's app icon in the formats the packages need, all
// generated by tools/icongen.
package icon

//go:generate go run ../../tools/icongen -out . -syso ../../rsrc_windows_amd64.syso

import (
	"embed"
	"image"
	"image/png"
	"strconv"
)

//go:embed png/doted-16.png png/doted-32.png png/doted-48.png png/doted-64.png png/doted-128.png png/doted-256.png
var files embed.FS

// Images returns the icon at several sizes, for the window's title bar and
// taskbar entry; the system picks the closest size.
func Images() ([]image.Image, error) {
	var imgs []image.Image
	for _, size := range []int{16, 32, 48, 64, 128, 256} {
		f, err := files.Open("png/doted-" + strconv.Itoa(size) + ".png")
		if err != nil {
			return nil, err
		}
		img, err := png.Decode(f)
		f.Close()
		if err != nil {
			return nil, err
		}
		imgs = append(imgs, img)
	}
	return imgs, nil
}
